apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec:
  volumeName: host-pv
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests: 
      storage: 1Gi